server:
  port: 8888

spring:
  application:
    name:
  ribbitmq:
    host: 127.0.0.1
    port: 5672
    userName: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-location: file://${user.home}/Desktop/Work/native-file-repo
        git:
#          uri: file:///Users/kimtaemin/Desktop/Work/git-local-repo
          uri: https://github.com/tmkim1/spring-cloud-config.git
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh